### ISSUE TITLE
cannot compile with rust 1.58.0-nightly

### ISSUE THREAD

**Issue by Pietro222222** [nonamescm/yex-lang#2]
```rs
yex-lang on  master [?] via 🦀 v1.58.0-nightly ➜ cargo r
   Compiling libc v0.2.103
   Compiling bitflags v1.2.1
   Compiling endian-type v0.1.2
   Compiling vm v0.1.0 (/home/pietro/programar/projetos-de-outros/yex-lang/vm)
   Compiling unicode-segmentation v1.8.0
   Compiling utf8parse v0.2.0
   Compiling nibble_vec v0.1.0
warning: the feature `inline_const` is incomplete and may not be safe to use and/or cause compiler crashes
 --> vm/src/lib.rs:2:12
  |
2 | #![feature(inline_const)]
  |            ^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #76001 <https://github.com/rust-lang/rust/issues/76001> for more information

   Compiling radix_trie v0.2.1
error[E0282]: type annotations needed
  --> vm/src/stack.rs:11:54
   |
11 |     const ARRAY_INIT: [MaybeUninit<T>; S] = [const { MaybeUninit::uninit() }; S];
   |                                                      ^^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `T`

For more information about this error, try `rustc --explain E0282`.
warning: `vm` (lib) generated 1 warning
error: could not compile `vm` due to previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
error: build faile
```
![image](https://user-images.githubusercontent.com/62407732/144711689-6f1727d7-1f83-446d-9c8d-9f7463bbd1bb.png)

**Comment by nonamescm** [comment]
fixed
